### PR TITLE
find / replace i'm not good at this stuf

### PR DESCRIPTION
**Pull request by JohnMica**
now it should be ok

### CODE REVIEW

**Comment by Wikiki** [comment]
Actually as you also modify the intend it's difficult to me to review your PR I don't get the real modification directly.

**Comment by JohnMica** [comment]
My bad man,

seems i’m using tabs and you’re using spaces.

i’ve closed the PR as my brain is not 100% here today.

but the issue i opened does happen anyhow and on Codepen you have the problem

https://codepen.io/JohnMica/pen/WMBeyj?editors=1010

Regards,

John Mica

**Comment by derevandal** [comment]
@JohnMica bro, your changes fixed this bug?
I don't see how change these variables from const to let can change anything.

**Comment by JohnMica** [comment]
Andre,

My changes don’t fix it. It was mostly so you can assign a different object to a variable. 
That’s why I closed the PR anyways. 
I’ll look into it (try to understand the code first) and see if I can manage to do something about it. 

Regards,

John Mica

**Pull request closed without merging**
