### PR TITLE
Fix failure in build

### PR DESCRIPTION
**Pull request by abetomo**
## Add package
The following error occurred for the added package.

```
Error: Cannot find module 'XXX'
```

## Fix failure in build
I get the following error.

```
[13:48:51] 'build:styles:copy' errored after 3.87 ms
[13:48:51] Error: File not found with singular glob: /path/bulma-carousel/src/sass/index.scss (if this was purposeful, use `allowEmpty` option)
```

### CODE REVIEW

**Comment by abetomo** [comment]
@Wikiki Thank you for the review.
I referred to the [bulma-steps](https://github.com/Wikiki/bulma-steps/blob/master/dist/css/bulma-steps.sass).
In `bulma-steps`, sass was included in dist, so it was included in this PR.
Should I not include sass?

**Comment by Wikiki** [comment]
I don't see the link with bulma-steps but Yes please update the PR to only include gulpfile.js and package.json.

thanks

**Comment by abetomo** [comment]
I updated.

**Comment by Wikiki** [comment]
Thanks

**Pull request merged**
